/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package ti.tinkerforge;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.KrollProxy;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.kroll.common.Log;

import com.tinkerforge.BrickletColor;
import com.tinkerforge.NotConnectedException;
import com.tinkerforge.TimeoutException;

// This proxy can be created by calling Tinkerforge.createExample({message: "hello world"})
@Kroll.proxy(creatableInModule = TinkerforgeModule.class)
public class BrickletColorProxy extends KrollProxy {
	private static final String LCAT = TinkerforgeModule.LCAT;
	private BrickletColor bColor;
	private BrickletUri brickletUri;

	public BrickletColorProxy() {
		super();
	}

	@Override
	public void handleCreationArgs(KrollModule createdInModule, Object[] args) {
		brickletUri = new BrickletUri(args);
		bColor = new BrickletColor(brickletUri.UID, brickletUri.ipConn);
		Log.d(LCAT, bColor.toString());

	}

	@Kroll.method
	public KrollDict getColor() {
		KrollDict res = new KrollDict();
		try {
			BrickletColor.Color color = bColor.getColor();
			;
			res.put("color", String.format("#%06X",
					(0xFFFFFF & android.graphics.Color.rgb(color.r, color.g,
							color.b))));
			res.put("ok", true);
			res.put("c", color.c);
			res.put("r", color.r);
			res.put("g", color.g);
			res.put("b", color.b);
			return res;
		} catch (TimeoutException e) {
			res.put("error", e.getMessage());
			e.printStackTrace();
			return res;
		} catch (NotConnectedException e) {
			e.printStackTrace();
			res.put("error", e.getMessage());
			return res;
		}
	}
}